POST http://localhost:3000/cashier
Content-Type: application/json
# Te voy a pasar un objeto de tipo JSON
{
  "id": "1asd2c4d5c7jk6d",
  "totalPrice": 6000,
  "date": "2020-01-01",
  "paymentMethod": "cash",
  "items": [
    {
      "id": 1,
      "name": "Capuccino",
      "price": 6000
    }
  ]
}



PATCH http://localhost:3000/cashier/update-cash-registrer
Content-Type: application/json
{
  "id": "1asd2c4d5c7jk6d",
  "paymentMethod": "credit card"
}

GET http://localhost:3000/cashier/credit/Mateo
  ?type=123&size=10&date=2025-09-25
  &price=15000&isPromo=true&promoCode=1234561