POST http://localhost:3000/auth/refresh
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYmZjMDQ1ZC0xZTkzLTQ3ZGQtYTFiYi0zYzBlZTkxOTJkMmUiLCJlbWFpbCI6IkxhdXJhIEJlbmF2aWRlcyIsInBhc3N3b3JkIjoiJDJiJDEwJEdiQ05ONFBySUo5SFJOc0VaWjE1SWVVdGwzOVdiZm1RbjRVQy9MYktOenVzVmhKV2IzbXJHIiwiaWF0IjoxNzYwMzIzMjQ1LCJleHAiOjE3NjA5MjgwNDV9.UIQ81W8dNV7RU9fZMDy1CYSIELhF12-cJNLfwgC1VzE