GET http://localhost:3000/user/get-all
Authorization: Bearer eJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzYmZjMDQ1ZC0xZTkzLTQ3ZGQtYTFiYi0zYzBlZTkxOTJkMmUiLCJlbWFpbCI6IkxhdXJhIEJlbmF2aWRlcyIsImlhdCI6MTc2MDMxMDI3NywiZXhwIjoxNzYwMzExMTc3fQ.w6Oz7MOiazDjVjtg71v_UxDhnQWHuoYOsBu_ommPhJI